name := "uscis-case-tracker"
version := "0.1.0"
scalaVersion := "2.13.14"

// Enable fs2-grpc plugin and BuildInfo
enablePlugins(Fs2Grpc, BuildInfoPlugin)

// BuildInfo configuration
buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion)
buildInfoPackage := "uscis"
buildInfoOptions += BuildInfoOption.BuildTime

// Fork JVM for run to ensure proper Cats Effect IOApp behavior
Compile / run / fork := true

val http4sVersion = "0.23.25"
val circeVersion = "0.14.6"
val armeriaVersion = "1.31.0" // Use latest Armeria for ScalaPB compatibility
val doobieVersion = "1.0.0-RC5"

libraryDependencies ++= Seq(
  // Cats Effect for functional programming
  "org.typelevel" %% "cats-effect" % "3.5.4",
  "org.typelevel" %% "cats-core" % "2.10.0",
  
  // HTTP Client (http4s)
  "org.http4s" %% "http4s-ember-client" % http4sVersion,
  "org.http4s" %% "http4s-circe" % http4sVersion,
  "org.http4s" %% "http4s-dsl" % http4sVersion,
  
  // JSON (Circe)
  "io.circe" %% "circe-core" % circeVersion,
  "io.circe" %% "circe-generic" % circeVersion,
  "io.circe" %% "circe-parser" % circeVersion,
  
  // Database - Doobie (functional JDBC layer for Cats Effect)
  "org.tpolecat" %% "doobie-core" % doobieVersion,
  "org.tpolecat" %% "doobie-hikari" % doobieVersion,  // HikariCP connection pool
  
  // Oracle JDBC Driver with all security extensions for wallet support
  // ojdbc11-production bundles: ojdbc11, oraclepki, osdt_core, osdt_cert
  "com.oracle.database.jdbc" % "ojdbc11-production" % "23.5.0.24.07" pomOnly(),
  "com.oracle.database.jdbc" % "ojdbc11" % "23.5.0.24.07",
  "com.oracle.database.security" % "oraclepki" % "23.5.0.24.07",
  
  // Armeria - unified HTTP/gRPC/gRPC-Web server
  // Supports HTTP/1.1, HTTP/2, gRPC, gRPC-Web on single port
  "com.linecorp.armeria" % "armeria" % armeriaVersion,
  "com.linecorp.armeria" % "armeria-grpc" % armeriaVersion,
  // Note: Exclude armeria-scalapb to avoid ScalaPB version conflicts
  // We use the standard grpc-java binding generated by fs2-grpc/scalapb
  
  // gRPC and Protobuf (for code generation, Armeria handles runtime)
  "com.thesamet.scalapb" %% "scalapb-runtime-grpc" % scalapb.compiler.Version.scalapbVersion,
  // Include well-known protobuf types (Timestamp, Duration, etc.)
  "com.thesamet.scalapb" %% "scalapb-runtime" % scalapb.compiler.Version.scalapbVersion % "protobuf",
  
  // Configuration
  "com.typesafe" % "config" % "1.4.3",
  
  // Logging
  "org.typelevel" %% "log4cats-slf4j" % "2.6.0",
  "ch.qos.logback" % "logback-classic" % "1.4.14",
  "org.slf4j" % "jul-to-slf4j" % "2.0.9", // Bridge JUL (used by gRPC/Netty) to SLF4J
  
  // Testing
  "org.scalatest" %% "scalatest" % "3.2.18" % Test,
  "org.typelevel" %% "cats-effect-testing-scalatest" % "1.5.0" % Test
)

// Assembly configuration for fat jar
assembly / assemblyJarName := "uscis-case-tracker.jar"
assembly / mainClass := Some("uscis.Main")

// Merge strategy for assembly (handle duplicates)
assembly / assemblyMergeStrategy := {
  case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard
  case PathList("META-INF", "services", _*) => MergeStrategy.concat
  case PathList("META-INF", _*) => MergeStrategy.discard
  case PathList("reference.conf") => MergeStrategy.concat
  case PathList("application.conf") => MergeStrategy.concat
  case PathList("logback.xml") => MergeStrategy.first
  case "module-info.class" => MergeStrategy.discard
  case x if x.endsWith(".proto") => MergeStrategy.first
  case x if x.endsWith(".class") => MergeStrategy.first
  case x =>
    val oldStrategy = (assembly / assemblyMergeStrategy).value
    oldStrategy(x)
}
